# Generated by Django 3.0.2 on 2020-01-06 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Logs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('client_id', models.CharField(max_length=100)),
                ('message_id', models.CharField(max_length=100)),
                ('room_id', models.CharField(max_length=100)),
                ('query_id', models.CharField(max_length=100)),
                ('question', models.TextField()),
                ('question_matched', models.TextField()),
                ('answer', models.TextField()),
                ('action', models.CharField(blank=True, max_length=100, null=True)),
                ('action_param', models.TextField(blank=True, null=True)),
                ('score', models.FloatField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
