# Generated by Django 3.0.2 on 2020-01-06 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elasticsearch_logs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='logs',
            name='action',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='logs',
            name='action_param',
            field=models.TextField(blank=True, null=True),
        ),
    ]
